### ISSUE TITLE
Public dataset change to private not syndicated

### ISSUE THREAD

**Issue by MrkGrgsn** [aptivate/ckanext-syndicate#3]
If you have an existing public dataset and then set the dataset Visibility to Private in the source repository, this change is not syndicated to the destination portal. The dataset continues to appear publicly in the destination portal.

I expect that a dataset made Private should no longer appear in the destination portal, either by being made private or by being deleted (I'm unsure which is most appropriate; it might depend on the circumstances).

**Comment by martinburchell** [comment]
Thanks for reporting this. It probably needs some thinking through. At the moment the plugin doesn't try to be too clever with this sort of thing.

**Comment by smotornyuk** [comment]
v2.0 allows you to decide whether dataset must be syndicated:
```
class MyPlugin(plugins.Plugin):
	plugins.implements(ISyndicate, inherit=True)

	def skip_syndication(
		self, package: model.Package, profile: Profile
	) -> bool:
		if should_be_syndicated(package):
			return False
		return True

	def prepare_package_for_syndication(
		self, package_id: str, data_dict: dict[str, Any], profile: Profile
	) -> dict[str, Any]:
		data_dict.pop("sensitive_field")
		return data_dict
```
