### ISSUE TITLE
How to coexist with another schema updating plugin?

### ISSUE THREAD

**Issue by nesnera** [aptivate/ckanext-syndicate#8]
I'd like to use ckanext-syndicate together with another plugin which updates schema but I unable realized it.
How to reproduce it
1) enable build in plugin `example_idatasetform` (appends country_code field, CKAN 2.7.0) 
2) enable `syndicate` plugin
3) publicate an dataset with syndicate flag = True
    plugin example_idatasetform works well - preserves country_code value
    as you can see at celery output syndication is activated but does nothing
4) if you change in `/usr/lib/ckan/default/src/ckan/ckanext/example_idatasetform/plugin.py` return value of `is_fallback()` to `False` behavior is reversed
   plugin example_idatasetform doesn't preserves country_code value
   syndication is OK

Do you have an idea how to solve it?

**Comment by martinburchell** [comment]
@nesnera soon we're going to need to address this exact issue on the CKAN site we've been developing - I can't give you a time frame yet unfortunately.

**Comment by smotornyuk** [comment]
The recommended way to handle this - using [ckanext-scheming](https://github.com/ckan/ckanext-scheming). In addition, you can use the ISyndicate interface and do not use the `syndicate` flag at all in rare cases:

```
class MyPlugin(plugins.Plugin):
	plugins.implements(ISyndicate, inherit=True)

	def skip_syndication(
		self, package: model.Package, profile: Profile
	) -> bool:
		if should_be_syndicated(package):
			return False
		return True

```
